version: '{build}'
environment:
  CLI_VERSION: latest
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
image: Visual Studio 2019
configuration:
    - Release
skip_tags: true
before_build:
    - dotnet tool install -g GitVersion.Tool
    - dotnet gitversion /l console /output buildserver
build_script:
    - dotnet build -c Release -p:Version=%GitVersion_NuGetVersion%
test_script:
    - dotnet test -c Release --no-build
artifacts:
- path: .\**\*.nupkg
  name: NuGet
nuget:
  disable_publish_on_pr: true
deploy:
- provider: NuGet
  api_key:
    secure: +CD+4G+gMInD/BjNvO24NW9u1udGdsx0fUi6bh0muNezQ9fP0sHnS1f96f0OXUy6
  on:
    branch:
    - master
    - /release\/[0-9]\.[0-9]/